
Loading training data...
Traceback (most recent call last):
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/SkinVenv/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 162, in __getattr__
    return self.__getitem__(key)
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/SkinVenv/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'NO_PIXELS'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/WandBSkinSegmentation.py", line 326, in model_pipeline
    model, train_loader, test_loader, loss_function, optimizer = make(config)
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/WandBSkinSegmentation.py", line 234, in make
    train, test = load_data(config, [], [])
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/WandBSkinSegmentation.py", line 84, in load_data
    train_images, train_gts = load_images(config, train_images, train_gts, base_path + "/TrainImages", base_path + "/TrainGroundTruth")
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/WandBSkinSegmentation.py", line 66, in load_images
    img = cv2.resize(img, (config.NO_PIXELS,config.NO_PIXELS), interpolation=cv2.INTER_CUBIC)
  File "/Users/mariekekopmels/Desktop/Uni/MScThesis/Code/Thesis/SkinVenv/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'NO_PIXELS'